#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Interactive onboarding wizard for BountyStrike v5 alpha testers.

Guides new operators through:
  - API key configuration (ANTHROPIC_API_KEY, platform keys)
  - RS256 keypair generation
  - First scope JWT issuance
  - Optional first-scan walkthrough

Usage:
    python scripts/init_wizard.py [--dry-run] [--update]

Options:
    --dry-run   Show what would be written without actually writing files
    --update    Re-run wizard to update existing configuration
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

try:
    from gen_scope_jwt import ensure_keys, issue_scope_jwt
except ImportError:
    print("ERROR: Could not import gen_scope_jwt. Run from repo root.", file=sys.stderr)
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env"
ENV_EXAMPLE = REPO_ROOT / ".env.example"

REQUIRED_KEYS = {
    "ANTHROPIC_API_KEY": "Anthropic API key (required for LLM operations)",
    "DATABASE_URL": "PostgreSQL connection string (e.g., postgresql://bs:password@127.0.0.1:5432/bountystrike)",
}

PLATFORM_KEYS = {
    "H1_API_TOKEN": "HackerOne API token (required for HackerOne programs)",
    "H1_USERNAME": "HackerOne username",
    "BUGCROWD_SESSION_COOKIE": "Bugcrowd session cookie",
    "INTIGRITI_PAT": "Intigriti Personal Access Token",
    "YESWEHACK_BEARER": "YesWeHack bearer token",
}


def _load_existing_env() -> dict[str, str]:
    """Load existing .env file if present."""
    if not ENV_FILE.exists():
        return {}

    env_vars = {}
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                env_vars[key.strip()] = value.strip()
    return env_vars


def _backup_env() -> Path | None:
    """Create an incremental backup of the existing .env file.

    Uses .env.backup.1, .env.backup.2, etc. so repeated --update runs
    never overwrite a previous backup.

    Returns the backup path, or None if no existing .env.
    """
    if not ENV_FILE.exists():
        return None

    # Find next backup number (preserve all previous backups)
    idx = 1
    while ENV_FILE.with_suffix(f".env.backup.{idx}").exists():
        idx += 1

    backup = ENV_FILE.with_suffix(f".env.backup.{idx}")
    shutil.copy2(ENV_FILE, backup)
    return backup


def _save_env(env_vars: dict[str, str], dry_run: bool = False) -> None:
    """Save environment variables to .env file."""
    if dry_run:
        print("\n[DRY RUN] Would write to .env:")
        for k, v in sorted(env_vars.items()):
            masked = v[:8] + "..." if len(v) > 8 else v
            print(f"  {k}={masked}")
        return

    # Create incremental backup if .env exists
    backup = _backup_env()
    if backup:
        print(f"Existing .env backed up to {backup.name}")

    with open(ENV_FILE, "w") as f:
        f.write("# BountyStrike v5 — Auto-generated by init wizard\n")
        f.write("# Edit manually or re-run: scripts/bs init --update\n\n")

        for key, value in sorted(env_vars.items()):
            f.write(f"{key}={value}\n")

    print(f"Configuration saved to {ENV_FILE}")


def _prompt(message: str, default: str = "", required: bool = True) -> str:
    """Interactive prompt with optional default."""
    while True:
        if default:
            user_input = input(f"{message} [{default}]: ").strip()
            if not user_input:
                return default
            return user_input
        else:
            user_input = input(f"{message}: ").strip()
            if user_input or not required:
                return user_input
            print("This field is required. Please enter a value.")


def _prompt_yes_no(message: str, default: bool = False) -> bool:
    """Yes/no prompt."""
    suffix = " [Y/n]" if default else " [y/N]"
    response = input(f"{message}{suffix}: ").strip().lower()
    if not response:
        return default
    return response in ("y", "yes")


def _collect_api_keys(existing: dict[str, str], update_mode: bool) -> dict[str, str]:
    """Interactive prompts for API keys."""
    print("\n=== API Key Configuration ===\n")
    env_vars = existing.copy()

    # Required keys
    for key, description in REQUIRED_KEYS.items():
        current = existing.get(key, "")
        if update_mode and current:
            if _prompt_yes_no(f"Keep existing {key}?", default=True):
                continue

        print(f"\n{description}")
        value = _prompt(key, default=current, required=True)
        env_vars[key] = value

    # Platform keys (optional)
    print("\n=== Platform API Keys (Optional) ===")
    print("Configure at least one platform to run scans.\n")

    for key, description in PLATFORM_KEYS.items():
        current = existing.get(key, "")
        if update_mode and current:
            action = _prompt(f"Keep existing {key}? [Y=keep / N=remove / E=edit]", default="Y").strip().upper()
            if action == "Y" or action == "":
                continue
            elif action == "N":
                env_vars.pop(key, None)
                print(f"  {key} removed.")
                continue
            # action == "E" falls through to edit below

        print(f"\n{description}")
        if _prompt_yes_no(f"Configure {key}?", default=bool(current)):
            value = _prompt(key, default=current, required=False)
            if value:
                env_vars[key] = value

    # Add default values for infrastructure if not present
    if "REDIS_HOST" not in env_vars:
        env_vars["REDIS_HOST"] = "127.0.0.1"
    if "REDIS_PORT" not in env_vars:
        env_vars["REDIS_PORT"] = "6379"
    if "SCOPE_JWT_PRIVATE_KEY_PATH" not in env_vars:
        env_vars["SCOPE_JWT_PRIVATE_KEY_PATH"] = "keys/scope_jwt_private.pem"
    if "SCOPE_JWT_PUBLIC_KEY_PATH" not in env_vars:
        env_vars["SCOPE_JWT_PUBLIC_KEY_PATH"] = "keys/scope_jwt_public.pem"

    return env_vars


def _generate_jwt(dry_run: bool, auto_proceed: bool = False) -> dict | None:
    """Interactive JWT generation flow."""
    print("\n=== Scope JWT Generation ===\n")
    print("Generate a scope JWT for your first target program.")

    if not auto_proceed and not _prompt_yes_no("Generate JWT now?", default=True):
        return None

    operator_id = _prompt("Operator ID (e.g., alice)", required=True)
    program_handle = _prompt("Program handle (e.g., acme-corp)", required=True)
    platform = _prompt("Platform", default="hackerone", required=True)

    print("\nTarget scope (at least one required):")
    wildcards_input = _prompt("Wildcard targets (comma-separated, e.g., *.acme.com)", required=False)
    hosts_input = _prompt("Exact hosts (comma-separated, e.g., app.acme.com)", required=False)

    wildcards = [w.strip() for w in wildcards_input.split(",") if w.strip()]
    hosts = [h.strip() for h in hosts_input.split(",") if h.strip()]

    if not wildcards and not hosts:
        print("ERROR: At least one wildcard or exact host required", file=sys.stderr)
        return None

    hours = float(_prompt("JWT expiry (hours)", default="168", required=True))
    rps = int(_prompt("Default rate limit (RPS)", default="5", required=True))

    if dry_run:
        print("\n[DRY RUN] Would generate JWT with:")
        print(f"  Operator: {operator_id}")
        print(f"  Program: {program_handle}")
        print(f"  Platform: {platform}")
        print(f"  Wildcards: {wildcards}")
        print(f"  Hosts: {hosts}")
        print(f"  Expiry: {hours}h, RPS: {rps}")
        return {"token": "DRY_RUN_TOKEN", "jti": "dry_run_jti"}

    # Generate keypair
    private_pem, _ = ensure_keys(force=False)

    # Issue JWT
    result = issue_scope_jwt(
        private_pem=private_pem,
        operator_id=operator_id,
        program_handle=program_handle,
        platform=platform,
        wildcards=wildcards,
        exact_hosts=hosts,
        default_rps=rps,
        expiry_hours=hours,
    )

    print("\n✓ JWT generated successfully")
    print(f"  JTI: {result['jti']}")
    print(f"  Expires: {result['expires_at']}")
    print(f"\nSCOPE_JWT={result['token']}")

    # Save to file
    jwt_file = REPO_ROOT / "scope_jwt.txt"
    with open(jwt_file, "w") as f:
        f.write(result["token"])
    print(f"\nToken saved to {jwt_file}")

    # Add program_handle and platform for first-scan walkthrough
    result["program_handle"] = program_handle
    result["platform"] = platform

    return result


def _offer_first_scan(jwt_result: dict, database_url: str, dry_run: bool) -> None:
    """Offer to launch a first test scan with guided walkthrough.

    Args:
        jwt_result: JWT data from _generate_jwt (contains token, program_handle, platform)
        database_url: PostgreSQL connection string from env
        dry_run: If True, show what would happen without actually running
    """
    print("\n=== First Scan Walkthrough ===\n")
    print("Would you like to launch a test scan now?")
    print("\nThis will:")
    print("  • Start the orchestrator with your JWT")
    print("  • Run recon-agent to discover assets")
    print("  • Run scanner-agent to find vulnerabilities")
    print("  • Save findings to the database")
    print("\nEstimated time: 15-60 minutes (depending on scope size)")
    print("You can monitor progress in the orchestrator output.\n")

    if not _prompt_yes_no("Launch first scan?", default=False):
        return

    # Check infrastructure readiness
    print("\nChecking prerequisites...")

    # Extract JWT data - handle both dict formats
    program_handle = jwt_result.get("program_handle", "unknown")
    platform = jwt_result.get("platform", "hackerone")
    scope_jwt = jwt_result.get("token", "")

    # Verify database connectivity
    docker_check = subprocess.run(
        ["docker", "compose", "ps", "--services", "--filter", "status=running"],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )

    running_services = set(docker_check.stdout.strip().split("\n")) if docker_check.stdout.strip() else set()
    required_services = {"postgres", "redis"}
    missing = required_services - running_services

    if missing:
        print(f"\n⚠ Infrastructure not ready. Missing services: {', '.join(missing)}")
        print("\nStart infrastructure first:")
        print("  cd", REPO_ROOT)
        print("  docker compose up -d")
        print("\nThen run the scan manually:")
        print(f"  export SCOPE_JWT=$(cat scope_jwt.txt)")
        print(f"  export PROGRAM_HANDLE={program_handle}")
        print(f"  export PLATFORM={platform}")
        print(f"  python scripts/orchestrator.py")
        return

    print("✓ Infrastructure running")
    print("✓ JWT ready")
    print("✓ Database configured")

    if dry_run:
        print("\n[DRY RUN] Would execute:")
        print(f"  PROGRAM_HANDLE={program_handle}")
        print(f"  PLATFORM={platform}")
        print(f"  SCOPE_JWT={scope_jwt[:20]}...")
        print(f"  DATABASE_URL={database_url}")
        print(f"  python scripts/orchestrator.py")
        return

    # Launch orchestrator
    print("\n" + "=" * 60)
    print("Launching orchestrator...")
    print("=" * 60 + "\n")

    env = os.environ.copy()
    env["PROGRAM_HANDLE"] = program_handle
    env["PLATFORM"] = platform
    env["SCOPE_JWT"] = scope_jwt
    env["DATABASE_URL"] = database_url

    try:
        result = subprocess.run(
            [sys.executable, "scripts/orchestrator.py"],
            env=env,
            cwd=REPO_ROOT,
            text=True,
        )

        if result.returncode == 0:
            print("\n✓ Scan completed successfully!")
            print("\nNext steps:")
            print("  • Review findings: python scripts/approve.py list")
            print("  • Approve T2 exploits: python scripts/approve.py approve <finding-id>")
        else:
            print(f"\n⚠ Scan exited with code {result.returncode}")
            print("Check logs above for errors. Common issues:")
            print("  • Missing platform API keys (H1_API_TOKEN, etc.)")
            print("  • Invalid scope targets")
            print("  • Network connectivity")
    except FileNotFoundError:
        print("\nERROR: Could not find orchestrator.py")
        print("Ensure you're running from the repository root")
    except KeyboardInterrupt:
        print("\n\nScan interrupted by user. Partial results may be in the database.")


def _show_next_steps(jwt_generated: bool) -> None:
    """Print next steps and feedback link."""
    print("\n" + "=" * 60)
    print("Setup complete! Next steps:")
    print("=" * 60)

    if jwt_generated:
        print("\n1. Start infrastructure (if not already running):")
        print("   docker compose up -d")
        print("\n2. Export your JWT:")
        print("   export SCOPE_JWT=$(cat scope_jwt.txt)")
        print("\n3. Run your first scan:")
        print("   export PROGRAM_HANDLE=<program-handle>")
        print("   export PLATFORM=<platform>")
        print("   python scripts/orchestrator.py")
        print("\n4. Review findings:")
        print("   python scripts/approve.py list")
    else:
        print("\n1. Generate a JWT:")
        print("   python scripts/gen_scope_jwt.py --program <handle> --operator <id>")
        print("\n2. Follow steps above to run scans")

    print("\n" + "=" * 60)
    print("Documentation:")
    print("  • Alpha Testing Guide: docs/runbooks/alpha-testing-guide.md")
    print("  • First Scan Walkthrough: docs/runbooks/first-scan-walkthrough.md")
    print("  • Troubleshooting: docs/runbooks/troubleshooting-guide.md")
    print("\nFeedback:")
    print("  Submit issues and suggestions via GitHub Discussions")
    print("  → https://github.com/bountystrike/bountystrike-v5/discussions")
    print("=" * 60 + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="init_wizard",
        description="Interactive onboarding wizard for BountyStrike v5",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--dry-run", action="store_true",
                       help="Show what would be written without writing files")
    parser.add_argument("--update", action="store_true",
                       help="Update existing configuration")
    args = parser.parse_args()

    print("=" * 60)
    print("BountyStrike v5 — Interactive Setup Wizard")
    print("=" * 60)

    existing = _load_existing_env()
    update_mode = args.update and bool(existing)

    if args.update and not existing:
        print("\nNo existing .env found. Running initial setup...\n")
        update_mode = False

    if update_mode:
        print(f"\nUpdate mode — {len(existing)} existing value(s) loaded from .env")
        print("You'll be asked whether to keep or change each value.")
        print("A backup will be created before any changes.\n")

    if existing and not args.update:
        print("\nExisting .env detected. Re-run with --update to modify.")
        if args.dry_run:
            print("Proceeding with JWT generation (dry-run mode)...\n")
        else:
            print("Continuing with JWT generation...\n")
        jwt_result = _generate_jwt(args.dry_run, auto_proceed=args.dry_run)

        # Offer first scan walkthrough if JWT was generated
        if jwt_result and "token" in jwt_result:
            database_url = existing.get("DATABASE_URL", "")
            if database_url:
                _offer_first_scan(jwt_result, database_url, args.dry_run)

        _show_next_steps(jwt_result is not None)
        return 0

    # Collect API keys
    env_vars = _collect_api_keys(existing, update_mode)
    _save_env(env_vars, args.dry_run)

    # Generate JWT
    jwt_result = _generate_jwt(args.dry_run)

    # Offer first scan walkthrough if JWT was generated
    if jwt_result and "token" in jwt_result:
        database_url = env_vars.get("DATABASE_URL", "")
        if database_url:
            _offer_first_scan(jwt_result, database_url, args.dry_run)

    # Show next steps
    _show_next_steps(jwt_result is not None)

    return 0


if __name__ == "__main__":
    sys.exit(main())
