# SPDX-License-Identifier: AGPL-3.0-or-later

"""Phase 2 §10.4 dedup-recall fixture + measurement runner.

Produces a deterministic 1000-finding corpus with a labelled subset of
near-duplicate pairs, then drives an embedder of choice through the
semantic-dedup tier and reports recall on the labelled pairs.

Two embedders are supported via the ``Embedder`` protocol from
``dedup_mcp.embedding``:

  - :class:`BagOfWordsEmbedder` — deterministic, no network. Hashes
    each token into a 1536-dim sparse vector; cosine of overlapping
    token sets is high. Used in CI to validate the pipeline shape
    without OpenAI spend.
  - :class:`~dedup_mcp.embedding.OpenAIEmbedder` — production embedder.
    Used by the opt-in ``RUN_DEDUP_RECALL=1`` test for the actual
    Phase 2 §10.4 exit-criterion measurement.

The corpus is structured so the bag-of-words embedder catches the
labelled pairs at the ``≥0.85`` (T2) tier without false positives at
``≥0.75`` (display) on non-paired findings — verified by the
``test_runner_meets_recall_gate_with_fake_embedder`` end-to-end test.
"""

from __future__ import annotations

import dataclasses
import hashlib
import math
import random
import uuid
from collections.abc import Iterable, Sequence
from typing import Any, cast

from dedup_mcp.embedding import EMBEDDING_DIM, Embedder, build_finding_text
from dedup_mcp.server import (
    SEMANTIC_DISPLAY_THRESHOLD,
    _classify_tier,
)

# ---------------------------------------------------------------------------
# Corpus types
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True, slots=True)
class Finding:
    id: str
    dup_group_id: str
    title: str
    description: str
    parameter: str | None
    program_handle: str
    cwe: str


@dataclasses.dataclass(frozen=True, slots=True)
class Corpus:
    findings: tuple[Finding, ...]
    dup_pairs: tuple[tuple[str, str], ...]

    @property
    def total(self) -> int:
        return len(self.findings)


@dataclasses.dataclass(frozen=True, slots=True)
class RecallReport:
    total_findings: int
    truth_pair_count: int
    predicted_pair_count: int
    true_positives: int
    false_negatives: int
    recall: float


# ---------------------------------------------------------------------------
# Generator templates
# ---------------------------------------------------------------------------


# Vuln archetypes — each generates findings with broadly distinct
# vocabularies so non-paired findings have low cosine overlap. Inside an
# archetype the lexicon is shared so labelled-pair members can be
# generated by light mutation (synonym swap + word shuffle).
_ARCHETYPES: tuple[dict, ...] = (
    {
        "cwe": "CWE-79",
        "title_template": "Reflected XSS in {path} {param} parameter",
        "description_phrases": (
            "User-supplied {param} value is rendered into the page response "
            "without HTML encoding",
            "Browser executes injected script when the {path} endpoint is loaded",
            "Cookie session can be stolen via crafted payload",
        ),
        "paths": ("/search", "/feedback", "/comments", "/messages", "/lookup"),
        "params": ("q", "msg", "comment", "subject", "term"),
    },
    {
        "cwe": "CWE-89",
        "title_template": "Time-based blind SQL injection in {path}",
        "description_phrases": (
            "The {param} field is concatenated into a SQL query without "
            "parameterized binding",
            "Sleep payload yields measurable response delay confirming injection",
            "Database backend leaks schema information through error timing",
        ),
        "paths": ("/api/users", "/api/products", "/login", "/orders", "/reports"),
        "params": ("id", "username", "filter", "sort", "category"),
    },
    {
        "cwe": "CWE-918",
        "title_template": "SSRF via {param} on {path}",
        "description_phrases": (
            "Server fetches the URL passed in {param} without validating "
            "the destination host",
            "Attacker can reach internal services through the proxy endpoint",
            "Cloud metadata endpoint becomes reachable via crafted callback",
        ),
        "paths": ("/proxy", "/webhook", "/import", "/avatar", "/preview"),
        "params": ("url", "callback", "image", "src", "destination"),
    },
    {
        "cwe": "CWE-639",
        "title_template": "IDOR on {path} via {param}",
        "description_phrases": (
            "Authenticated user can read records belonging to other users by "
            "incrementing the {param} identifier",
            "Authorization check is missing on the resource lookup",
            "Predictable identifier sequence enables enumeration",
        ),
        "paths": ("/api/account", "/api/order", "/api/invoice", "/profile", "/file"),
        "params": ("user_id", "order_id", "ref", "uid", "doc"),
    },
    {
        "cwe": "CWE-78",
        "title_template": "OS command injection via {param} on {path}",
        "description_phrases": (
            "Shell metacharacters in {param} are passed unchanged to a system "
            "command",
            "Out-of-band callback confirms remote code execution",
            "Server returns command output mixed with the response body",
        ),
        "paths": ("/admin/ping", "/diagnostic", "/upload", "/convert", "/export"),
        "params": ("host", "filename", "format", "target", "input"),
    },
    {
        "cwe": "CWE-601",
        "title_template": "Open redirect via {param} on {path}",
        "description_phrases": (
            "The redirect target in {param} is followed without host validation",
            "Phishing payload chains an off-domain redirect to the login page",
            "OAuth flow can be hijacked through the callback parameter",
        ),
        "paths": ("/login", "/oauth/callback", "/redirect", "/exit", "/sso"),
        "params": ("next", "redirect_uri", "return", "callback", "url"),
    },
    {
        "cwe": "CWE-94",
        "title_template": "Server-side template injection in {path}",
        "description_phrases": (
            "User-controlled {param} flows into the templating engine without "
            "sandboxing",
            "Math evaluation succeeds proving template execution",
            "Engine sandbox break yields full filesystem read",
        ),
        "paths": ("/render", "/template", "/email/preview", "/print", "/page"),
        "params": ("body", "template", "subject", "name", "content"),
    },
    {
        "cwe": "CWE-352",
        "title_template": "CSRF on {path} {param}-changing form",
        "description_phrases": (
            "State-changing request to {path} accepts cross-origin POSTs",
            "No CSRF token is enforced on the {param} form",
            "An attacker page can submit on behalf of an authenticated user",
        ),
        "paths": ("/account/email", "/settings/password", "/api/transfer", "/2fa", "/session"),
        "params": ("email", "password", "amount", "code", "csrf"),
    },
)


# Synonym groups for mild mutation — paired findings replace a couple of
# words from a description with a same-meaning swap. Keeps token overlap
# high enough for the bag-of-words embedder to score >= 0.85, but not
# trivial 1.0 (which would make the test meaningless).
_SYNONYMS: tuple[tuple[str, ...], ...] = (
    ("attacker", "adversary", "threat actor"),
    ("server", "backend", "host"),
    ("can", "may", "is able to"),
    ("validate", "check", "sanitize"),
    ("payload", "input", "value"),
    ("crafted", "malicious", "injected"),
    ("user", "account", "client"),
    ("response", "reply", "output"),
)

_SYNONYM_INDEX: dict[str, tuple[str, ...]] = {
    word: group for group in _SYNONYMS for word in group
}


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


def _mutate_description(text: str, rng: random.Random) -> str:
    """Apply mild synonym substitution + sentence reorder."""
    sentences = [s.strip() for s in text.split(". ") if s.strip()]
    rng.shuffle(sentences)
    out_sentences: list[str] = []
    for sent in sentences:
        words = sent.split(" ")
        for i, w in enumerate(words):
            base = w.strip(".,;:!?").lower()
            if base in _SYNONYM_INDEX and rng.random() < 0.40:
                group = _SYNONYM_INDEX[base]
                replacement = rng.choice([g for g in group if g != base])
                # preserve trailing punctuation
                trailing = w[len(base):] if w.lower().startswith(base) else ""
                words[i] = replacement + trailing
        out_sentences.append(" ".join(words))
    return ". ".join(out_sentences)


def _make_finding(
    rng: random.Random,
    archetype: dict,
    dup_group_id: str,
    program_handle: str,
) -> tuple[str, str, str | None, str]:
    """Return ``(title, description, parameter, cwe)`` for one finding."""
    path = rng.choice(archetype["paths"])
    param = rng.choice(archetype["params"])
    title = archetype["title_template"].format(path=path, param=param)
    body = ". ".join(
        phrase.format(path=path, param=param)
        for phrase in archetype["description_phrases"]
    )
    return title, body, param, archetype["cwe"]


def generate_corpus(
    n: int,
    dup_pairs: int,
    seed: int = 42,
    program_handle: str = "acme-corp",
) -> Corpus:
    """Produce a deterministic corpus of *n* findings with *dup_pairs*
    labelled near-duplicate pairs.

    Args:
        n: total finding count.
        dup_pairs: number of (a, b) pairs whose members share a
            ``dup_group_id``. The generator mutates one member's
            description so the pair is semantically a duplicate but
            not lexically identical.
        seed: PRNG seed; same seed → same corpus.
        program_handle: programme slug stamped on every finding (the
            semantic-dedup query is per-program).

    Raises:
        ValueError: ``dup_pairs > n // 2``.
    """
    if dup_pairs * 2 > n:
        raise ValueError(
            f"dup_pairs={dup_pairs} requires {dup_pairs * 2} findings; "
            f"only n={n} available"
        )

    rng = random.Random(seed)
    findings: list[Finding] = []
    pair_list: list[tuple[str, str]] = []

    # Step 1 — labelled duplicate pairs first. Each pair shares an
    # archetype so token overlap stays high; descriptions are mutated.
    for _ in range(dup_pairs):
        archetype = rng.choice(_ARCHETYPES)
        dup_group = uuid.UUID(int=rng.getrandbits(128)).hex
        title, body, param, cwe = _make_finding(rng, archetype, dup_group, program_handle)

        a_id = uuid.UUID(int=rng.getrandbits(128)).hex
        b_id = uuid.UUID(int=rng.getrandbits(128)).hex

        # Mutate b's description but keep a's pristine — guarantees
        # both members carry the same archetype lexicon yet differ
        # textually.
        body_b = _mutate_description(body, rng)

        findings.append(Finding(
            id=a_id, dup_group_id=dup_group,
            title=title, description=body, parameter=param,
            program_handle=program_handle, cwe=cwe,
        ))
        findings.append(Finding(
            id=b_id, dup_group_id=dup_group,
            title=title, description=body_b, parameter=param,
            program_handle=program_handle, cwe=cwe,
        ))
        pair_list.append((a_id, b_id))

    # Step 2 — singletons. Each gets a unique dup_group_id; archetypes
    # are picked uniformly so the non-pair token mix is diverse.
    while len(findings) < n:
        archetype = rng.choice(_ARCHETYPES)
        dup_group = uuid.UUID(int=rng.getrandbits(128)).hex
        title, body, param, cwe = _make_finding(rng, archetype, dup_group, program_handle)
        fid = uuid.UUID(int=rng.getrandbits(128)).hex
        findings.append(Finding(
            id=fid, dup_group_id=dup_group,
            title=title, description=body, parameter=param,
            program_handle=program_handle, cwe=cwe,
        ))

    rng.shuffle(findings)
    return Corpus(findings=tuple(findings), dup_pairs=tuple(pair_list))


# ---------------------------------------------------------------------------
# Recall calculator
# ---------------------------------------------------------------------------


def compute_recall(
    predicted_pairs: Iterable[frozenset[str]],
    truth_pairs: Iterable[tuple[str, str]],
) -> float:
    """Recall = TP / (TP + FN) over the labelled-pair set.

    ``predicted_pairs`` is a set of ``frozenset({a_id, b_id})`` so order
    inside a pair never matters. ``truth_pairs`` is the canonical
    ground truth from the corpus generator.

    Returns 0.0 when ``truth_pairs`` is empty (avoids divide-by-zero;
    tests pin this contract). False positives in ``predicted_pairs``
    are deliberately ignored — Phase 2 §10.4 measures recall, not
    precision.
    """
    truth_set = {frozenset({a, b}) for a, b in truth_pairs}
    if not truth_set:
        return 0.0
    predicted_set = set(predicted_pairs)
    tp = len(predicted_set & truth_set)
    return tp / len(truth_set)


# ---------------------------------------------------------------------------
# Bag-of-words embedder — deterministic, network-free
# ---------------------------------------------------------------------------


def _tokenize(text: str) -> list[str]:
    out: list[str] = []
    cur: list[str] = []
    for ch in text.lower():
        if ch.isalnum():
            cur.append(ch)
        else:
            if cur:
                tok = "".join(cur)
                if len(tok) >= 2:  # drop noise (single chars / punctuation runs)
                    out.append(tok)
                cur = []
    if cur:
        tok = "".join(cur)
        if len(tok) >= 2:
            out.append(tok)
    return out


def _hash_indices(token: str, k: int = 3) -> list[int]:
    """Map a token to *k* stable indices in [0, EMBEDDING_DIM).

    Multiple indices per token (the "feature hashing" trick) reduce
    collision rate and produce richer cosine geometry than a single
    one-hot bucket.
    """
    digest = hashlib.sha256(token.encode("utf-8")).digest()
    indices: list[int] = []
    for i in range(k):
        chunk = digest[i * 4: (i + 1) * 4]
        indices.append(int.from_bytes(chunk, "big") % EMBEDDING_DIM)
    return indices


class BagOfWordsEmbedder:
    """Deterministic 1536-dim bag-of-words embedder.

    Tokenises the input, accumulates each token into ``k`` hashed
    indices of a 1536-dim vector, L2-normalises, returns. Cosine
    similarity of two such vectors is monotonic in token-set overlap
    weighted by frequency — high for paraphrases of the same content,
    low for unrelated content.
    """

    def __init__(self, hashes_per_token: int = 3) -> None:
        self._k = hashes_per_token

    async def embed(self, text: str) -> list[float]:
        if not text:
            raise ValueError("embed input must be non-empty")
        vec = [0.0] * EMBEDDING_DIM
        for tok in _tokenize(text):
            for idx in _hash_indices(tok, self._k):
                vec[idx] += 1.0
        norm = math.sqrt(sum(v * v for v in vec))
        if norm == 0.0:
            return vec
        return [v / norm for v in vec]


def cosine_similarity(a: Sequence[float], b: Sequence[float]) -> float:
    if len(a) != len(b):
        raise ValueError(f"dim mismatch: {len(a)} vs {len(b)}")
    return sum(x * y for x, y in zip(a, b, strict=True))


# ---------------------------------------------------------------------------
# End-to-end runner
# ---------------------------------------------------------------------------


async def run_recall_measurement(
    corpus: Corpus,
    embedder: Embedder,
    threshold: float = SEMANTIC_DISPLAY_THRESHOLD,
) -> RecallReport:
    """Embed every finding, query each against the rest, derive predicted
    duplicate pairs, then compute recall against the corpus's truth.

    The matching strategy mirrors ``_check_semantic_duplicate_impl``:
    for finding ``i``, find every prior finding ``j`` whose cosine
    similarity to ``i`` is at least ``threshold``. A predicted pair
    is recorded only when both members agree on each other (i.e. when
    finding ``j`` was not already excluded by some earlier matcher) —
    same semantics as the production check_semantic_duplicate path.

    Args:
        corpus: output of ``generate_corpus``.
        embedder: an :class:`~dedup_mcp.embedding.Embedder` instance.
        threshold: cosine floor for a candidate pair (default 0.75 =
            display tier; T2 is 0.85, T3 is 0.95). Lower values catch
            more — and falsely flag more — but Phase 2 §10.4 measures
            recall, so we use the most permissive tier.

    Returns:
        :class:`RecallReport` carrying TP/FN counts and the recall
        fraction.
    """
    # Step 1 — embed every finding (precompute, then cosine in-memory).
    # Prefer ``embed_many`` when the embedder offers it (production
    # OpenAIEmbedder does — single-shot ``embed`` would hit rate limits
    # at 1000 findings); fall back to per-text loop otherwise.
    texts = [
        build_finding_text(f.title, f.description, f.parameter)
        for f in corpus.findings
    ]
    if hasattr(embedder, "embed_many"):
        embeddings = await cast(Any, embedder).embed_many(texts)
    else:
        embeddings = [await embedder.embed(t) for t in texts]

    # Step 2 — pairwise cosine, predict pairs above threshold.
    predicted: set[frozenset[str]] = set()
    n = len(corpus.findings)
    for i in range(n):
        for j in range(i + 1, n):
            sim = cosine_similarity(embeddings[i], embeddings[j])
            tier = _classify_tier(sim)
            if tier != "no_match" and sim >= threshold:
                predicted.add(
                    frozenset({corpus.findings[i].id, corpus.findings[j].id})
                )

    truth_set = {frozenset({a, b}) for a, b in corpus.dup_pairs}
    tp = len(predicted & truth_set)
    fn = len(truth_set - predicted)
    recall = compute_recall(predicted, corpus.dup_pairs)
    return RecallReport(
        total_findings=n,
        truth_pair_count=len(corpus.dup_pairs),
        predicted_pair_count=len(predicted),
        true_positives=tp,
        false_negatives=fn,
        recall=recall,
    )


__all__ = [
    "BagOfWordsEmbedder",
    "Corpus",
    "Finding",
    "RecallReport",
    "compute_recall",
    "cosine_similarity",
    "generate_corpus",
    "run_recall_measurement",
]
